import Head from 'next/head'
import { useSelector } from 'react-redux'
import { AppState, dispatch } from '~/state/store'
import { Inter } from 'next/font/google'
import { memo, useEffect } from 'react'
import { fetchPosts, setPosts } from '~/state/duck/post'

const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const { posts, loading } = useSelector((state: AppState) => state.posts);

  useEffect(() => {
    dispatch(fetchPosts(3))
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        Hello Build
        {loading ? <>Loading...</> : <>{posts?.title}</>}
        <div>
          <button onClick={() => dispatch(fetchPosts(6))}>click</button>
        </div>
      </main>
    </>
  )
}

export default memo(Home);